INSERT INTO Profiles(ProfileID, Username, AvatarID, Score, FirstName, LastName, Email, DateJoined)
VALUES (
	'31725395-d91c-4463-8f4a-67a2c690c8a4',
	'JohnSmith',
	4,
	1025,
	'John',
	'Smith',
	'john.smith@bu.edu',
	GETUTCDATE()
);

DECLARE @ProfileID NVARCHAR(128)
SET @ProfileID = '31725395-d91c-4463-8f4a-67a2c690c8a4'

-- POPULATE TagCategory TABLE
-- Only needs to run if Sam's code doesn't initialize this table
INSERT INTO [dbo].[TagCategories]([TagCategoryID], [Name])
VALUES (1, 'Genre')
INSERT INTO [dbo].[TagCategories]([TagCategoryID], [Name])
VALUES (2, 'Element')
INSERT INTO [dbo].[TagCategories]([TagCategoryID], [Name])
VALUES (3, 'Actor/Actress')
INSERT INTO [dbo].[TagCategories]([TagCategoryID], [Name])
VALUES (4, 'Director')
INSERT INTO [dbo].[TagCategories]([TagCategoryID], [Name])
VALUES (5, 'Era')
INSERT INTO [dbo].[TagCategories]([TagCategoryID], [Name])
VALUES (6, 'Location')

-- POPULATE Avatars TABLE
-- Only needs to run if Sam's code doesn't initialize this table
INSERT INTO [dbo].[Avatars]([AvatarID], [Name], [ImageURL])
VALUES (1, 'Extra','~/Images/Avatars/Extra.png')
INSERT INTO [dbo].[Avatars]([AvatarID], [Name], [ImageURL])
VALUES (2, 'Supporting Role','~/Images/Avatars/SupportingRole.png')
INSERT INTO [dbo].[Avatars]([AvatarID], [Name], [ImageURL])
VALUES (3, 'Movie Star','~/Images/Avatars/MovieStar.png')
INSERT INTO [dbo].[Avatars]([AvatarID], [Name], [ImageURL])
VALUES (4, 'Oscar Winner','~/Images/Avatars/OscarWinner.png')


-- POPULATE Movies TABLE

INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('The Shawshank Redemption', 1994, 'Morgan Freeman. Nough Said.', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Star Wars: Episode VI - Return of the Jedi', 1983, 'The third installment in the original series', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('The Hobbit: An Unexpected Journey', 2012, 'An unexpected journe', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('The Lord of the Rings: The Fellowship of the Ring', 2001, 'My precious!', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Buffy the Vampire Slayer', 1992, 'Not the show', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Safe House', 2012, 'Denzel', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Spider-Man', 2002, 'The other one is too new', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('The Avengers', 2012, 'Lots of superheroes', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Iron Man', 2008, 'One superhero made of iron', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Back to the Future', 1985, 'Youre a slacker, McFly', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Wedding Crashers', 2005, 'Classic Vince Vaughn/Owen Wilson banter.', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Top Gun', 1986, 'Tom Cruise...pre-crazy', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Footloose', 1984, 'Bacon + Loggins cant be beat!', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Taken', 2008, 'Liam neeson goes bananas on some fools', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Avatar', 2009, 'Blue creatures. Ew.', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('The Hunger Games', 2012, 'I dont know, havent seen it', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('The Big Lebowski', 1998, 'The Dude abides.', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('The Lego Movie', 2014, 'EVERYTHING IS AWESOME', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('The English Patient', 1996, 'Steamy', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Titanic', 1997, 'Baby Leo, homewrecking like only he can', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('The Terminator', 1984, '2029, huh? Sure.', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Terminator 2: Judgment Day', 1991, 'A much nicer Arnold.', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Mystic River', 2003, 'Wicked sad.', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Shine a Light', 2008, 'Marty LOVES the Stones.', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('The Song Remains the Same', 1976, 'Zep trips out and crushes MSG', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Goldfinger', 1964, 'Everything he touches turns to excitement!', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Forrest Gump', 1994, 'Stupid is as stupid does.', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Space Jam', 1996, 'Jordan!', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Weekend at Bernies', 1989, 'So infamous, the made a song about it', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Armageddon', 1998, 'Michael Bay, just getting warming up', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Raiders of the Lost Ark', 1981, 'Starring Han Solo as Indy', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Godzilla', 1954, 'The original', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Gone with the Wind', 1939, 'Frankly, my dear, I dont give a damn', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('O Brother, Where Art Thou?', 2000, 'He is a man of constant sorrow', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Fistful of Dollars', 1964, 'The timeless, dark western classic', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Psycho', 1960, 'Karmas a...well, you know.', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('Young Frankenstein', 1974, 'No, its pronounced eye-gor.', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('The Godfather', 1972, 'An offer you cant refuse.', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('The Departed', 2006, 'Im not a cop!', @ProfileID, GETUTCDATE(), 'Joe Director')
INSERT INTO [dbo].[Movies]([Title], [Year], [Description], [SubmitterID], [DateAdded], [Director])
VALUES ('American Hustle', 2013, 'Sleaze pays', @ProfileID, GETUTCDATE(), 'Joe Director')


-- POPULATE Tags TABLE
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Action', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Drama', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Comedy', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Romance', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Adventure', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Crime', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Fiction', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Fantasy', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Sci-Fi', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (2, 'Awesomeness', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (2, 'Terror', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (2, 'Awe', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (2, 'Good Photography', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (2, 'Stuff', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (5, '1970s', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (5, '1950s', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (6, 'California', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (3, 'Michael J. Fox', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Animated', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Sports', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Horror', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (1, 'Documentary', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (2, 'Flying', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (2, 'War', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (2, 'Kidnapping', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (2, 'Doomsday', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (2, 'Dancing', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (2, 'Time travel', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (3, 'Tom Hanks', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (3, 'Arnold Schwartzenegger', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (3, 'Leonardo DiCaprio', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (3, 'Jennifer Lawrence', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (4, 'James Cameron', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (4, 'Robert Zemeckis', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (4, 'Clint Eastwood', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (4, 'Martin Scorcese', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (5, '2010s', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (5, '2000s', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (5, '1980s', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (5, '1990s', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (5, 'Pre-WWII', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (5, 'Future', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (6, 'Fictional Location', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (6, 'Outer Space', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (6, 'New York', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (6, 'Los Angeles', GETUTCDATE(), @ProfileID)
INSERT INTO [dbo].[Tags]([CategoryID], [Name], [CreatedDateTime], [SubmitterID])
VALUES (6, 'Boston', GETUTCDATE(), @ProfileID)


-- POPULATE TagApplications TABLE
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 1, 1, 1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 2, 2, 0, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 3, 3, -2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 4, 4, -2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 5, 5, -1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 6, 6, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 7, 7, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 8, 8, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 9, 9, 1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 10, 10, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 11, 1, -5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 12, 2, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 13, 3, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 1, 4, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 3, 6, -4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 4, 7, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 5, 8, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 6, 9, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 7, 10, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 8, 1, -3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 9, 2, 7, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 10, 3, 1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 11, 4, -2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 12, 5, 0, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 13, 6, 0, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 1, 7, 1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 2, 8, 0, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 3, 9, -1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 4, 10, 0, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 5, 1, -1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 6, 2, 1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 7, 3, 6, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 8, 4, 6, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 9, 5, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 10, 6, -1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 11, 7, -3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 12, 8, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 13, 9, 1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 14, 11, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 16, 11, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 17, 11, 1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 18, 11, 7, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 19, 19, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 19, 29, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 19, 34, -4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 20, 29, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 20, 18, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 22, 25, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 1, 15, 6, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 1, 32, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 1, 23, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 1, 17, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 1, 16, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 26, 31, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 26, 22, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 26, 23, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 25, 18, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 25, 15, 6, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 2, 1, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 2, 20, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 2, 21, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 2, 34, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 4, 11, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 4, 12, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 4, 13, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 4, 20, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 4, 21, 7, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 4, 28, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 4, 34, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 4, 41, 1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 6, 39, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 6, 41, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 6, 40, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 6, 27, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 6, 25, -3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 17, 12, -3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 17, 13, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 17, 18, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 17, 22, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 17, 23, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 28, 11, 6, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 28, 22, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 28, 23, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 29, 28, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 29, 39, -5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 31, 21, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 31, 40, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 31, 18, -3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 32, 17, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 32, 41, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 32, 34, -4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 36, 40, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 36, 25, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 33, 21, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 33, 22, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 33, 23, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 33, 16, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 39, 11, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 16, 33, 4, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 44, 29, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 44, 31, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 44, 2, 6, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 47, 24, 3, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 47, 40, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 27, 7, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 19, 7, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 27, 12, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 39, 14, 6, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 27, 14, 5, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 27, 19, 1, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 27, 30, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 27, 41, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 27, 11, 2, GETUTCDATE())
INSERT INTO [dbo].[TagApplications]([SubmitterID], [TagID], [MovieID], [Score], [SubmittedDateTime])
VALUES (@ProfileID, 39, 30, 2, GETUTCDATE())

-- POPULATE Votes TABLE
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 1, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 1, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 1, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 2, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 3, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 4, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 5, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 6, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 7, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 8, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 9, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 10, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 11, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 12, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 13, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 14, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 16, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 17, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 18, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 18, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 19, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 20, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 21, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 22, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 22, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 22, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 22, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 23, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 24, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 25, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 26, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 27, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 27, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 27, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 28, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 28, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 28, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 29, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 30, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 31, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 32, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 32, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 32, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 32, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 33, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 33, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 33, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 33, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 34, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 34, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 34, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 34, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 34, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 35, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 36, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 37, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 37, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 37, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 38, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 38, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 39, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 40, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 42, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 42, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 42, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 42, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 43, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 43, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 43, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 43, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 44, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 44, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 44, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 44, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 44, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 44, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 45, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 45, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 45, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 46, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 46, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 47, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 47, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 47, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 47, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 47, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 47, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 48, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 48, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 48, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 48, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 49, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 49, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 50, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 50, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 51, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 51, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 51, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 52, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 53, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 53, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 53, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 54, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 54, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 54, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 54, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 55, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 56, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 56, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 56, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 57, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 58, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 59, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 59, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 59, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 60, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 60, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 60, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 60, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 60, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 60, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 60, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 61, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 62, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 63, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 63, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 63, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 64, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 64, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 65, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 65, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 66, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 66, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 66, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 67, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 67, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 67, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 68, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 68, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 68, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 68, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 68, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 68, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 68, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 69, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 71, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 71, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 71, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 71, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 71, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 70, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 72, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 73, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 73, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 73, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 73, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 74, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 74, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 74, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 75, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 75, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 76, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 77, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 77, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 77, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 77, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 78, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 78, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 79, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 79, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 79, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 80, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 80, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 80, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 80, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 81, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 81, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 82, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 83, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 83, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 83, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 83, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 83, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 84, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 85, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 86, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 86, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 86, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 87, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 87, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 87, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 87, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 88, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 88, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 88, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 88, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 88, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 88, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 89, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 89, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 89, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 90, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 90, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 90, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 90, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 91, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 91, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 91, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 92, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 92, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 92, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 93, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 93, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 93, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 94, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 94, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 94, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 94, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 95, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 95, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 96, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 96, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 96, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 96, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 97, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 97, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 97, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 97, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 97, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 98, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 98, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 99, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 100, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 100, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 100, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 101, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 101, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 101, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 102, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 103, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 103, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 104, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 104, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 104, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 105, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 105, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 106, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 106, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 106, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 106, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 106, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 107, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 107, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 108, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 108, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 108, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 109, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 109, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 110, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 110, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 110, 0, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 111, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 111, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 111, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 111, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 111, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 111, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 111, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 111, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 112, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 113, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 113, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 113, 1, GETUTCDATE())
INSERT INTO [dbo].[Votes]([SubmitterID], [TagApplicationID], [IsUpvote], [VotedDateTime])
VALUES (@ProfileID, 114, 1, GETUTCDATE())
